# Numpy Tutorial

## What is NumPy?
- NumPy is the fundamental package for scientific computing with Python. Among other things, it includes:
  - A powerful N-dimensional array object.
  - Sophisticated (broadcasting) functions.
  - Tools for integrating C/C++ and Fortran code.
  - Useful linear algebra, Fourier transform, and random number capabilities.
- One of its strengths: Ndarray
  - One of the most important features of NumPy is its N-dimensional array object, ndarray, which is a collection of data of the same type indexed by a tuple of non-negative integers. The ndarray object is a multidimensional array used to hold elements of the same type. Each element in the ndarray occupies the same amount of memory space.
- Another strength: Slicing and Indexing
  - The contents of ndarray objects can be accessed and modified by indexing or slicing, just like Python lists. The ndarray array can be indexed using integers from 0 to n. Slice objects can be created using the built-in slice function, setting the start, stop, and step parameters to extract a portion of the original array.

# NumPy Primer - 1
- NumPy
- Arrays
    - Generating arrays
    - Data type of arrays
    - Rank & Shape of arrays

## 1. NumPy
- Fundamental package for scientific computing with Python. NumPy stands for "Numerical Python"
- NumPy contains...
    - a powerful N-dimensional array object
    - sophisticated (broadcasting) functions
    - tools for integrating C/C++ and Fortran code
    - useful linear algebra, Fourier transform, and random number capabilities
- Official documentation: https://docs.scipy.org/doc/numpy-1.13.0/reference/

In [13]:
# importing numpy 
# numpy is imported using alias 'np' in most cases
import numpy as np

## 2. Arrays
- NumPy arrays are similar to Python lists, but has some restrictions 
    - e.g., same data types should be inserted in each array
- Like lists, multi-dimensional arrays can be generated. But usually, less than 4-dimensional are used. 
    - Mostly 1-dimensional (vectors) or 2-dimensional (matrices) are used
    
<br>
<img src="http://community.datacamp.com.s3.amazonaws.com/community/production/ckeditor_assets/pictures/332/content_arrays-axes.png" stype= "width: 400px"/>

### Generating arrays
- from lists
- from numpy functions

In [14]:
# arrays can be generated by converting list into array
a1 = np.array([1, 2, 3])    # generate 1-D array
print(type(a1))
print(a1)

<class 'numpy.ndarray'>
[1 2 3]


In [15]:
# creating multi-dim arrays from multi-dim lists
a2 = np.array([[1, 2], [3, 4]])                    # 2-D array
print(a2)
a3 = np.array([[[1,2], [3,4]], [[5,6],[7,8]]])     # 3-D array
print(a3)

[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [16]:
# creating arrays from built-in functions
a4 = np.ones((2))          # create array with all elements equal to 1
print(a4)
a5 = np.zeros((2,3))       # create array with all element equal to 0
print(a5)
a6 = np.full((2,2), 5)     # create array with all element equal to 5
print(a6)
a7 = np.random.randn(3)   # create array with random elements (0-1)
print(a7)

[1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[5 5]
 [5 5]]
[ 0.55510244 -0.44386528  1.01252783]


### Data type of arrays
- Most general data types for numpy numerical array are int or float
- If one wants to store string values, set ```dtype``` to ```np.str_``` or use ```np.chararray()``` 

In [17]:
a8 = np.array([1, 2, 3])          # integer array
print(a8.dtype)
a9 = np.array([1.0, 2.0, 3.0])    # float array
print(a9.dtype)

int32
float64


In [18]:
# data types can be assigned when creating array
a10 = np.array([1], dtype = np.int64)
print(a10)
a11 = np.array([1, 2, 3], dtype = np.float64)    # converts each value into float
print(a11)
a12 = np.array(['x', 'y', 'z'], dtype = np.str_) # creating string array
print(a12)
a13 = np.array([5, 'a'], dtype = np.object)      # inserting Python objects into array
print(a13)

[1]
[1. 2. 3.]
['x' 'y' 'z']
[5 'a']


c:\ProgramData\anaconda3\envs\jupyter-notebook\lib\site-packages\ipykernel_launcher.py:8: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


### Rank & Shape of arrays
- ```rank``` of array equals to number of dimensions (i.e., ```axes```) of array
    - axis
        - Each "coordinate" to index/slice array. 
        - For *n*-dimensional array, ```axes``` equal to ```{0, 1, 2, ..., n-1}```
    - Heuristically, ```rank``` equals to number of '['s in array instance
- ```shape``` of an array designates size of each dimension. 
    - In other words, how many elements fit into each axis

- For example, consider case of two-dimensional array, hence matrix.
    - ```shape``` of matrix would be ```(N, M)```. Thus ```rank``` = 2
    - Size of ```axis 0``` equals to ```N```. 
        - This means number of rows equals to ```N```.
    - Size of ```axis 1``` equals to ```M```.
        - This means number of columns equals to ```M```.

<br>    


In [19]:
# case of 1-D array; trivial
a14 = np.array([2, 4, 6, 8, 10])
print(a14.ndim)                    # rank = 1
print(a14.shape)                   # shape = (5,)

1
(5,)


In [20]:
# case of 2-D array
a15 = np.array([[1, 2, 3], [4, 5, 6]])
print(a15.ndim)                    # rank 2
print(a15.shape)                   # shape = (2,3)

2
(2, 3)


In [ ]:
# case of 3-D array
a16 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(a16.ndim)
print(a16.shape)

3
(2, 2, 2)


### Exercise 1-1.
- Create random vector (i.e., 1-D array) with length 20.
- Print ```rank```, ```shape```, and ```dtype``` of array
- Sort array in ascending order and print out result
- Sort array in descending order and print out result

In [ ]:
## Your answer


1 (20,) float64
[-3.00319374 -2.05366469 -1.26217056 -1.14643774 -0.98926241 -0.97091875
 -0.45922554 -0.35779958 -0.17584653  0.04017682  0.25780194  0.25969196
  0.38004598  0.56767284  0.82867208  0.88375878  0.94831422  1.39066303
  1.92697196  2.48483769]
[ 2.48483769  1.92697196  1.39066303  0.94831422  0.88375878  0.82867208
  0.56767284  0.38004598  0.25969196  0.25780194  0.04017682 -0.17584653
 -0.35779958 -0.45922554 -0.97091875 -0.98926241 -1.14643774 -1.26217056
 -2.05366469 -3.00319374]


### Exercise 1-2.
- Create a 3-D array with ```shape (2, 2, 2)``` containing integers from 0 to 7
- Print ```rank```, ```shape```, and ```dtype``` of array

In [ ]:
## Your answer


[0 1 2 3 4 5 6 7]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
3 (2, 2, 2) int32


## Quiz 1.
- create a 3-D array with shape (3, 3, 3) including numbers from 0 to 26
- Print ```rank```, ```shape```, and ```dtype``` of array


In [1]:
## Your answer
